default:
    @just --list

build:
    go build -o dist/s3up-server ./cmd/server
    go build -o dist/s3up ./cmd/client

build-linux:
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/s3up-server-linux ./cmd/server
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/s3up-linux ./cmd/client

test:
    go test -v ./test/...

test-cover:
    go test -v -coverprofile=coverage.out -coverpkg=./internal/... ./test/...
    go tool cover -func=coverage.out

test-cover-html:
    go test -v -coverprofile=coverage.out -coverpkg=./internal/... ./test/...
    go tool cover -html=coverage.out -o coverage.html
    @echo "Coverage report written to coverage.html"

test-system:
    cd test/system && bash run.sh

clean:
    rm -rf dist/
